apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    app: mysql-app
spec:
  replicas: 3
  selector:
    app: mysql-app
    deployment: v1
  template:
    metadata:
      labels:
        app: mysql-app
        deployment: v1
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          env:
            -
             name: MYSQL_ALLOW_EMPTY_PASSWORD
             valueFrom: 
               configMapKeyRef:
                 key: mysql.root.empty.password
                 name: mysql-config-2
          name: mysql
          image: mysql
          ports:
            -
              containerPort: 3306

