apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
    type: front-end
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
     name: myapp
     labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
