apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        -
          env:
            -
             name: MYSQL_ROOT_PASSWORD
             value: mysql
          name: nginx
          image: mysql
          ports:
            -
              containerPort: 3306
