apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
    -
      image: nginx
      name: nginx
      volumeMounts:
        -
          mountPath: /git-repo
          name: git-volume


  volumes:
    -
     gitRepo:
       repository: "https://github.com/4msahsan/kubernetes-volume"
       revision: ""
     name: git-volume
