apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: normal
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/foo
  resource:
    requests:
      storage: 2G1
