apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /var/lib/nfs-share
    server: 10.0.2.100
    readOnly: false
